import os
import uuid
from typing import Dict, Any
from pptx import Presentation as PptxPresentation
from pptx.util import Inches, Pt
from app.models.core import Presentation

class ExportService:
    def __init__(self, db=None):
        self.db = db # Kept for future DB writes if needed

    async def export_presentation(self, presentation: Presentation, presentation_data: Dict[str, Any]) -> str:
        prs = PptxPresentation()
        
        # Add Title Slide
        title_slide_layout = prs.slide_layouts[0]
        slide = prs.slides.add_slide(title_slide_layout)
        title = slide.shapes.title
        subtitle = slide.placeholders[1]
        
        title.text = presentation_data.get("title", "Untitled Presentation")
        subtitle.text = "Generated by EduDeck AI"
        
        # Add Content Slides
        for slide_data in presentation_data.get("slides", []):
            slide_layout = prs.slide_layouts[1] # Title and Content layout
            slide = prs.slides.add_slide(slide_layout)
            
            # Title
            title_shape = slide.shapes.title
            if title_shape:
                title_shape.text = slide_data.get("title", "")
                
            # Content
            body_shape = slide.placeholders[1]
            tf = body_shape.text_frame
            content_bullets = slide_data.get("content", [])
            if isinstance(content_bullets, list):
                tf.text = "\n".join(f"• {bp}" for bp in content_bullets)
            else:
                tf.text = str(content_bullets)
                
            # Speaker Notes
            notes_slide = slide.notes_slide
            if notes_slide and "speaker_notes" in slide_data:
                notes_slide.notes_text_frame.text = slide_data["speaker_notes"]

        filename = f"presentation_{uuid.uuid4()}.pptx"
        
        # Save locally in a public static directory for download
        # Assuming we run this from backend root
        os.makedirs("public/downloads", exist_ok=True)
        file_path = os.path.join("public/downloads", filename)
        prs.save(file_path)
        
        return f"http://localhost:8080/downloads/{filename}"
